### ISSUE TITLE
xubuntu 18.04 gnuplot windows take focus and use 100% cpu so you cant break out ^C   

### ISSUE THREAD

**Issue by osde8info** [vsergeev/luaradio#55] opened 2019-12-26 20:22 UTC
$ luaradio examples/rtlsdr_wbfm_mono.lua 102.2e6

gnuplot windows take focus and use 100% cpu so you cant break out ^C  

i will try and create a PR with a switch to enable gnuplot (with a default of off)

$ luaradio --platform
luajit          LuaJIT 2.1.0-beta3
os              Linux
arch            x64
page size       4096
cpu count       1
cpu model       Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz
features
    fftw3f      true    fftw-3.3.7-sse2-avx
    volk        true    1.3 (sse4_2_64_mmx_orc)
    liquid      false

$ luaradio --version
LuaRadio 0.6.0 - Vanya A. Sergeev. https://luaradio.io

**Comment by vsergeev** [comment] 2020-03-23 00:14
Closing as duplicate of #26. I think it would be best to consolidate the discussion there.

**Closed by vsergeev** 2020-03-23 00:14 UTC
